package com.cc_testj.demo.mybatis.dao;

import com.cc_testj.demo.mybatis.model.Words;
import com.cc_testj.demo.mybatis.model.WordsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eng_exercise_t_words
     *
     * @mbg.generated Mon Nov 20 15:50:01 CST 2017
     */
    long countByExample(WordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eng_exercise_t_words
     *
     * @mbg.generated Mon Nov 20 15:50:01 CST 2017
     */
    int deleteByExample(WordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eng_exercise_t_words
     *
     * @mbg.generated Mon Nov 20 15:50:01 CST 2017
     */
    int deleteByPrimaryKey(Integer num);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eng_exercise_t_words
     *
     * @mbg.generated Mon Nov 20 15:50:01 CST 2017
     */
    int insert(Words record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eng_exercise_t_words
     *
     * @mbg.generated Mon Nov 20 15:50:01 CST 2017
     */
    int insertSelective(Words record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eng_exercise_t_words
     *
     * @mbg.generated Mon Nov 20 15:50:01 CST 2017
     */
    List<Words> selectByExample(WordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eng_exercise_t_words
     *
     * @mbg.generated Mon Nov 20 15:50:01 CST 2017
     */
    Words selectByPrimaryKey(Integer num);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eng_exercise_t_words
     *
     * @mbg.generated Mon Nov 20 15:50:01 CST 2017
     */
    int updateByExampleSelective(@Param("record") Words record, @Param("example") WordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eng_exercise_t_words
     *
     * @mbg.generated Mon Nov 20 15:50:01 CST 2017
     */
    int updateByExample(@Param("record") Words record, @Param("example") WordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eng_exercise_t_words
     *
     * @mbg.generated Mon Nov 20 15:50:01 CST 2017
     */
    int updateByPrimaryKeySelective(Words record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eng_exercise_t_words
     *
     * @mbg.generated Mon Nov 20 15:50:01 CST 2017
     */
    int updateByPrimaryKey(Words record);
}