package com.cc_testj.demo.mybatis.model;

public class Words {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column eng_exercise_t_words.num
	 * @mbg.generated  Mon Nov 20 17:31:01 CST 2017
	 */
	private Integer num;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column eng_exercise_t_words.word
	 * @mbg.generated  Mon Nov 20 17:31:01 CST 2017
	 */
	private String word;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column eng_exercise_t_words.phonetic
	 * @mbg.generated  Mon Nov 20 17:31:01 CST 2017
	 */
	private String phonetic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column eng_exercise_t_words.definition
	 * @mbg.generated  Mon Nov 20 17:31:01 CST 2017
	 */
	private String definition;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column eng_exercise_t_words.eng_sentence
	 * @mbg.generated  Mon Nov 20 17:31:01 CST 2017
	 */
	private String engSentence;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column eng_exercise_t_words.chn_sentence
	 * @mbg.generated  Mon Nov 20 17:31:01 CST 2017
	 */
	private String chnSentence;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column eng_exercise_t_words.num
	 * @return  the value of eng_exercise_t_words.num
	 * @mbg.generated  Mon Nov 20 17:31:01 CST 2017
	 */
	public Integer getNum() {
		return num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column eng_exercise_t_words.num
	 * @param num  the value for eng_exercise_t_words.num
	 * @mbg.generated  Mon Nov 20 17:31:01 CST 2017
	 */
	public void setNum(Integer num) {
		this.num = num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column eng_exercise_t_words.word
	 * @return  the value of eng_exercise_t_words.word
	 * @mbg.generated  Mon Nov 20 17:31:01 CST 2017
	 */
	public String getWord() {
		return word;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column eng_exercise_t_words.word
	 * @param word  the value for eng_exercise_t_words.word
	 * @mbg.generated  Mon Nov 20 17:31:01 CST 2017
	 */
	public void setWord(String word) {
		this.word = word;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column eng_exercise_t_words.phonetic
	 * @return  the value of eng_exercise_t_words.phonetic
	 * @mbg.generated  Mon Nov 20 17:31:01 CST 2017
	 */
	public String getPhonetic() {
		return phonetic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column eng_exercise_t_words.phonetic
	 * @param phonetic  the value for eng_exercise_t_words.phonetic
	 * @mbg.generated  Mon Nov 20 17:31:01 CST 2017
	 */
	public void setPhonetic(String phonetic) {
		this.phonetic = phonetic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column eng_exercise_t_words.definition
	 * @return  the value of eng_exercise_t_words.definition
	 * @mbg.generated  Mon Nov 20 17:31:01 CST 2017
	 */
	public String getDefinition() {
		return definition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column eng_exercise_t_words.definition
	 * @param definition  the value for eng_exercise_t_words.definition
	 * @mbg.generated  Mon Nov 20 17:31:01 CST 2017
	 */
	public void setDefinition(String definition) {
		this.definition = definition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column eng_exercise_t_words.eng_sentence
	 * @return  the value of eng_exercise_t_words.eng_sentence
	 * @mbg.generated  Mon Nov 20 17:31:01 CST 2017
	 */
	public String getEngSentence() {
		return engSentence;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column eng_exercise_t_words.eng_sentence
	 * @param engSentence  the value for eng_exercise_t_words.eng_sentence
	 * @mbg.generated  Mon Nov 20 17:31:01 CST 2017
	 */
	public void setEngSentence(String engSentence) {
		this.engSentence = engSentence;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column eng_exercise_t_words.chn_sentence
	 * @return  the value of eng_exercise_t_words.chn_sentence
	 * @mbg.generated  Mon Nov 20 17:31:01 CST 2017
	 */
	public String getChnSentence() {
		return chnSentence;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column eng_exercise_t_words.chn_sentence
	 * @param chnSentence  the value for eng_exercise_t_words.chn_sentence
	 * @mbg.generated  Mon Nov 20 17:31:01 CST 2017
	 */
	public void setChnSentence(String chnSentence) {
		this.chnSentence = chnSentence;
	}
}